version: '2.19.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 8089:5432

  client-microservice:
    image: client-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - db
